/* DEMO ONLY - Backend integration pending.
   No authentication, network mutations, analytics SDK, persistence or payments.
   All actions below change this page's memory only and reset on reload/logout. */
(() => {
  'use strict';
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>Number(v).toLocaleString('en-US');
  const units=AWPresentation.buildUnits(projects),query=new URLSearchParams(location.search);
  let data=AWPresentation.createPortalState(projects),role='marketer',page='home',signedIn=false,leadPage=0,adFilter='all',adSearch='',selectedAd=null,noticeTimer,dialogOrigin,uploadUrls=[];
  const menu={marketer:[['home','الرئيسية'],['ads','إعلاناتي'],['add','إضافة إعلان'],['leads','العملاء المحتملون'],['performance','الأداء'],['commissions','العمولات'],['account','الحساب'],['logout','تسجيل الخروج']],admin:[['home','الرئيسية'],['projects','المشاريع'],['units','الوحدات'],['marketers','المسوقون'],['ads','مراجعة الإعلانات'],['featured','الإعلانات المميزة'],['leads','العملاء المحتملون'],['analytics','التحليلات والحملات']]};
  const status=s=>`<span class="status ${['معتمد','معتمدة','مدفوعة','نشط','تم التواصل'].includes(s)?'good':['مرفوض','منتهي','مغلق'].includes(s)?'bad':'wait'}">${esc(s)}</span>`;
  const metric=(title,value,detail='')=>`<article class="stat"><p>${title}</p><div class="metric">${value}</div><small>${detail}</small></article>`;
  const table=(headers,rows,caption='')=>`<div class="table-scroll" role="region" aria-label="${esc(caption||headers.join('، '))}" tabindex="0"><table>${caption?`<caption>${caption}</caption>`:''}<thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">لا توجد نتائج مطابقة.</td></tr>`}</tbody></table></div>`;
  const flow=items=>`<div class="flow">${items.map((s,i)=>`${i?'<i aria-hidden="true">←</i>':''}<span>${s}</span>`).join('')}</div>`;
  const panel=(title,body,extra='')=>`<section class="panel"><div class="panel-heading"><h2>${title}</h2>${extra}</div>${body}</section>`;
  function notify(message){$('#portalNotice').textContent=message;$('#portalNotice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#portalNotice').hidden=true,5500);}
  function dialog(title,html){dialogOrigin=document.activeElement;$('#portalDialogTitle').textContent=title;$('#portalDialogContent').innerHTML=html;$('#portalDialog').showModal();}
  $('#closePortalDialog').addEventListener('click',()=>$('#portalDialog').close());
  $('#portalDialog').addEventListener('close',()=>{if(dialogOrigin?.isConnected)dialogOrigin.focus({preventScroll:true});});
  function releaseUploads(){uploadUrls.forEach(URL.revokeObjectURL);uploadUrls=[];}
  function nav(next){releaseUploads();page=next;$('#portalNav').classList.remove('open');$('#sidebarToggle').setAttribute('aria-expanded','false');render();$('#portalContent').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
  function showWorkspace(){ $('#loginView').hidden=true;$('#workspace').hidden=false;render(); }
  function switchRole(){releaseUploads();role=role==='admin'?'marketer':'admin';page='home';if(role==='admin'||signedIn)showWorkspace();else{$('#workspace').hidden=true;$('#loginView').hidden=false;}$('#roleSwitch').textContent=role==='admin'?'عرض المسوق':'عرض الإدارة';}
  $('#roleSwitch').addEventListener('click',switchRole);
  $('#loginForm').addEventListener('submit',event=>{event.preventDefault();if(!event.currentTarget.reportValidity())return;signedIn=true;role='marketer';$('#loginPassword').value='';showWorkspace();});
  $('#sidebarToggle').addEventListener('click',()=>{const open=$('#portalNav').classList.toggle('open');$('#sidebarToggle').setAttribute('aria-expanded',String(open));});
  function logout(){releaseUploads();data.ads.forEach(a=>a.images.forEach(URL.revokeObjectURL));data=AWPresentation.createPortalState(projects);signedIn=false;role='marketer';page='home';leadPage=0;adFilter='all';adSearch='';selectedAd=null;$('#portalNav').classList.remove('open');$('#sidebarToggle').setAttribute('aria-expanded','false');$('#roleSwitch').textContent='عرض الإدارة';$('#workspace').hidden=true;$('#loginView').hidden=false;$('#loginEmail').value='presenter@example.com';$('#loginPassword').value='presentation';notify('انتهت جلسة العرض وتمت إعادة بياناتها.');}
  function marketerStats(){const views=data.ads.reduce((n,a)=>n+a.views,0);return `<div class="stats">${metric('الإعلانات',data.ads.length,'جميع حالات الإعلان')}${metric('المشاهدات',num(views),'ضمن بيانات العرض')}${metric('العملاء المحتملون',data.leads.length,'اهتمامات مرتبطة بالإعلانات')}${metric('معدل التحويل',AWPresentation.rate(data.leads.length,views)+'%','العملاء المحتملون ÷ المشاهدات')}</div>`;}
  function bars(rows){const max=Math.max(1,...rows.map(r=>r[1]));return `<div class="bar-list">${rows.map(([name,value])=>`<div class="row"><div class="bar-label"><span>${esc(name)}</span><bdi>${num(value)}</bdi></div><div class="bar-track"><span style="width:${value/max*100}%"></span></div></div>`).join('')}</div>`;}
  function analytics(){const c=AWPresentation.campaigns,totals=AWPresentation.totals(c),rank=projects.map(p=>[p.name,data.ads.filter(a=>a.projectId===p.id).reduce((n,a)=>n+a.views,0)]).sort((a,b)=>b[1]-a[1]);return `<div class="stats">${metric('إجمالي الزيارات',num(totals.visits),'قنوات العرض مجتمعة')}${metric('العملاء المحتملون',num(totals.leads),'بيانات عرض')}${metric('طلبات الاهتمام',num(totals.requests),'جميع الحملات')}${metric('Conversion Rate',AWPresentation.rate(totals.leads,totals.visits)+'%','العملاء المحتملون ÷ الزيارات')}</div><div class="dashboard-grid">${panel('أكثر المشاريع مشاهدة',bars(rank.slice(0,4)))}${panel('مصادر الزيارات',bars(c.map(x=>[x.name,x.visits])))}</div>${panel('أداء الحملات',table(['الحملة','الزيارات','Leads','طلبات الاهتمام','التحويل'],c.map(x=>[x.name,num(x.visits),num(x.leads),num(x.requests),AWPresentation.rate(x.leads,x.visits)+'%']),'مؤشرات توضيحية لعرض تجربة التحليلات'))}<br>${panel('أكثر الوحدات مشاهدة',table(['الوحدة / الإعلان','المشروع','المشاهدات'],[...data.ads].sort((a,b)=>b.views-a.views).slice(0,5).map(a=>[esc(a.title),projects.find(p=>p.id===a.projectId)?.name||'إعلان مستقل',num(a.views)])))}`;}
  function adsTable(){const rows=data.ads.filter(a=>(adFilter==='all'||a.status===adFilter)&&(!adSearch||[a.title,a.city,a.district].join(' ').includes(adSearch)));return `<div class="list-toolbar"><label>الحالة<select id="adStatusFilter"><option value="all">جميع الحالات</option>${['مسودة','تحت المراجعة','معتمد','مرفوض','منتهي'].map(s=>`<option ${s===adFilter?'selected':''}>${s}</option>`).join('')}</select></label><label>بحث<input id="adSearch" value="${esc(adSearch)}" placeholder="العقار أو الحي"></label>${role==='marketer'?'<button class="button" data-page="add">إضافة إعلان</button>':''}</div>${table(['العقار','الموقع','السعر','الحالة','المشاهدات','الإجراء'],rows.map(a=>[`${esc(a.title)}${a.status==='معتمد'?'<div class="subtle">منشور ضمن عرض البوابة</div>':''}`,esc(a.city+' · '+a.district),num(a.price)+' ريال',status(a.status),num(a.views),`<div class="actions"><button class="button secondary small" data-ad="${a.id}">التفاصيل</button>${role==='admin'&&a.status==='تحت المراجعة'?`<button class="button small" data-approve="${a.id}">اعتماد</button><button class="button danger small" data-reject="${a.id}">رفض</button>`:role==='marketer'?`<button class="button secondary small" data-upgrade="${a.id}">ترقية</button>`:''}</div>`]),'إعلانات الجلسة — لا تمثل نشرًا فعليًا')}`;}
  function addForm(){return panel('إضافة إعلان عقاري',`<form id="adForm" onsubmit="return false"><div class="form-grid"><label class="full">عنوان الإعلان<input name="title" required maxlength="100"></label><label>نوع العقار<select name="type"><option>شقة</option><option>فيلا</option><option>دور</option><option>أرض</option><option>مكتب</option></select></label><label>المدينة<input name="city" required maxlength="40" value="جدة"></label><label>الحي<input name="district" required maxlength="60"></label><label>السعر (ريال)<input name="price" type="number" required min="1" max="1000000000" step="any"></label><label>المساحة (م²)<input name="area" type="number" required min="1" max="10000000" step="any"></label><label>عدد الغرف<input name="rooms" type="number" required min="0" max="100" step="1"></label><label>نوع العرض<select name="offer"><option>بيع</option><option>إيجار</option></select></label><label>التصنيف<select name="stage"><option>جاهزة</option><option>تحت الإنشاء</option><option>إعادة بيع</option></select></label><label>رقم التواصل<input name="phone" type="tel" inputmode="tel" required pattern="[0-9٠-٩+() -]{8,25}" maxlength="25" dir="ltr"></label><label class="full">وصف العقار<textarea name="description" rows="4" required minlength="10" maxlength="1800"></textarea></label><label class="full">الصور<input id="adImages" type="file" accept="image/png,image/jpeg,image/webp" multiple><span class="form-note">حتى 6 صور، 5 ميجابايت للصورة. معاينة داخل الجهاز فقط.</span></label><div id="imagePreviews" class="image-previews full"></div></div><p class="error" id="adError" role="alert"></p><div class="actions"><button type="submit" class="button">إرسال للمراجعة</button><button type="button" class="button secondary" data-page="ads">إلغاء</button></div></form>`);}
  function plans(){return `<p class="subtle">${selectedAd?'الإعلان: '+esc(data.ads.find(a=>a.id===selectedAd)?.title):'اختر التصوّر المناسب لإعلانك.'} — لا يوجد دفع أو اشتراك فعلي.</p><br><div class="plans">${[['Basic','إعلان عادي',['عرض في دليل العقارات','لوحة أداء الإعلان']],['Featured','إعلان مميز',['شارة إعلان مميز','ظهور أوضح في نتائج البحث']],['Premium','ظهور في الصفحة الرئيسية',['مساحة عرض بارزة','أولوية الظهور داخل المنصة']]].map(([name,title,benefits],i)=>`<article class="plan ${i===1?'featured':''}"><span class="eyebrow">${name}</span><h3>${title}</h3><p>السعر يحدد لاحقًا</p><ul>${benefits.map(b=>`<li>${b}</li>`).join('')}</ul><button class="button ${i===1?'':'secondary'}" data-plan="${name}">معاينة الباقة</button></article>`).join('')}</div>`;}
  function leads(){const rows=data.leads.slice(leadPage*10,leadPage*10+10);return panel('العملاء المحتملون',table(['العميل','العقار','تاريخ الطلب','المصدر','الحالة'],rows.map(l=>[esc(l.name),esc(data.ads.find(a=>a.id===l.adId)?.title||'عقار'),l.date,esc(l.source),`<select data-lead-status="${l.id}" aria-label="حالة ${esc(l.name)}">${['جديد','تم التواصل','متابعة','مغلق'].map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select>`]),'أسماء افتراضية لعرض مسار متابعة العميل')+`<div class="pagination"><button class="button secondary small" data-lead-page="-1" ${leadPage===0?'disabled':''}>السابق</button><span>${leadPage*10+1}–${Math.min((leadPage+1)*10,data.leads.length)} من ${data.leads.length}</span><button class="button secondary small" data-lead-page="1" ${(leadPage+1)*10>=data.leads.length?'disabled':''}>التالي</button></div>`);}
  function adminProjects(){return panel('المشاريع المعروضة',table(['المشروع','الموقع','المرحلة','الوحدات','السعر يبدأ من','الإجراء'],projects.map(p=>[p.name,p.city+' · '+p.district,p.status,num(units.filter(u=>u.projectId===p.id).reduce((n,u)=>n+u.quantity,0)),p.startingPrice?num(p.startingPrice)+' ريال':'اتصل للسعر',`<button class="button secondary small" data-project-detail="${p.id}">عرض الوحدات</button>`])));}
  function unitsTable(list=units){return table(['الخيار','المشروع','التصنيف','الحالة','العدد','المساحة'],list.map(u=>[u.name,projects.find(p=>p.id===u.projectId).name,u.stage,status(u.status),u.quantity,u.area+' م²']),'خيارات وحدات سيناريو العرض');}
  function render(){
    $('#workspaceLabel').textContent=role==='admin'?'لوحة الإدارة':'بوابة المسوقين';$('#pageEyebrow').textContent=role==='admin'?'إدارة المنصة':'مسوق العرض';$('#roleSwitch').textContent=role==='admin'?'عرض المسوق':'عرض الإدارة';
    $('#portalNav').innerHTML=menu[role].map(([id,title],i)=>`<button data-page="${id}" ${id===page?'aria-current="page"':''}><span class="nav-index">${String(i+1).padStart(2,'0')}</span>${title}</button>`).join('');
    $('#pageTitle').textContent=page==='upgrade'?'ترقية الإعلان':menu[role].find(m=>m[0]===page)?.[1]||'الرئيسية';$('#pageDescription').textContent=role==='admin'?'نظرة متصلة على المشاريع والمسوقين وأداء المنصة.':'إعلاناتك وعملاؤك وخطوتك القادمة، بوضوح.';
    let html='';
    if(page==='home'&&role==='marketer')html=marketerStats()+`<div class="dashboard-grid">${panel('رحلة إعلانك',flow(['إضافة','مراجعة','اعتماد','نشر','عملاء','أداء','عمولة'])+'<p class="subtle">تابع كل مرحلة من لوحة واحدة.</p><br><button class="button" data-page="add">أضف إعلانًا جديدًا</button>')}${panel('طلبات المتابعة',`<h2>${data.leads.filter(l=>l.status!=='جديد').length} طلبًا قيد المتابعة أو مكتملًا</h2><p class="subtle">من أصل ${data.leads.length} اهتمامًا</p><br><button class="button secondary" data-page="leads">استعرض العملاء</button>`)}</div>`+panel('آخر الإعلانات',table(['العقار','الحالة','المشاهدات'],data.ads.slice(-5).reverse().map(a=>[esc(a.title),status(a.status),num(a.views)])));
    else if(page==='home')html=`<div class="stats">${metric('المشاريع',projects.length)}${metric('خيارات الوحدات',units.length,`${num(units.reduce((total,u)=>total+u.quantity,0))} وحدة ضمن مجموعات العرض`)}${metric('المسوقون',data.marketers.length)}${metric('بانتظار المراجعة',data.ads.filter(a=>a.status==='تحت المراجعة').length)}</div><div class="dashboard-grid">${panel('مساحة قرار واحدة',flow(['المشاريع','الوحدات','المسوقون','الإعلانات','العملاء','التحليلات'])+'<button class="button" data-page="ads">مراجعة الإعلانات</button>')}${panel('رحلة العميل والمستثمر',flow(['البحث','المشروع / الوحدة','الاهتمام','CRM','فريق المتابعة'])+flow(['الاستثمار','الفرصة','المشروع','الاستشارة','CRM']))}</div>${panel('امتداد المنصة مستقبلًا','<div class="architecture"><div>الموقع<small>البحث والاهتمام</small></div><div>تطبيق الجوال<small>تصوّر مستقبلي</small></div><div>بوابة المسوق<small>الإعلان والمتابعة</small></div><div>لوحة الإدارة<small>الإشراف والتحليلات</small></div></div>')}<br>${analytics()}`;
    else if(page==='ads')html=panel(role==='admin'?'مراجعة الإعلانات':'إعلاناتي',adsTable());
    else if(page==='add')html=addForm();
    else if(page==='upgrade')html=plans();
    else if(page==='leads')html=leads();
    else if(page==='performance')html=marketerStats()+panel('الطلبات',`<h2>${data.leads.filter(l=>l.status!=='جديد').length} طلبًا قيد المتابعة أو مكتملًا</h2><p class="subtle">الاهتمامات التي انتقلت من حالة جديد إلى التواصل أو المتابعة أو الإغلاق.</p>`)+panel('أداء الإعلانات',table(['الإعلان','المشاهدات','العملاء','التحويل'],data.ads.map(a=>{const count=data.leads.filter(l=>l.adId===a.id).length;return [esc(a.title),num(a.views),count,AWPresentation.rate(count,a.views)+'%'];})));
    else if(page==='commissions')html=panel('العمولات',table(['الصفقة','العقار','قيمة الصفقة','العمولة','الحالة'],data.commissions.map(c=>['AW-'+c.id,esc(data.ads.find(a=>a.id===c.adId)?.title),num(c.value)+' ريال',num(c.commission)+' ريال',status(c.status)]),'قيم توضيحية فقط؛ لا تمثل مستحقات أو تحويلات مالية'));
    else if(page==='account')html=panel('الحساب',`<form id="accountForm" onsubmit="return false"><div class="form-grid"><label>الاسم<input name="name" value="مسوق العرض" required maxlength="80"></label><label>البريد<input type="email" value="presenter@example.com" readonly></label><label class="full">نبذة<textarea name="bio" maxlength="400">حساب مخصص لاستعراض رحلة المسوق داخل المنصة.</textarea></label></div><br><button class="button">معاينة التحديث</button></form>`);
    else if(page==='analytics')html=analytics();
    else if(page==='projects')html=adminProjects();
    else if(page==='units')html=panel('الوحدات',unitsTable());
    else if(page==='marketers')html=panel('إدارة المسوقين',table(['المسوق','الإعلانات','الحالة','الإجراء'],data.marketers.map((m,i)=>[esc(m.name),i===0?data.ads.length:m.ads,status(m.status),`<button class="button secondary small" data-marketer="${i}">${m.status==='نشط'?'تعليق':'تفعيل'}</button>`])));
    else if(page==='featured')html=panel('إدارة الإعلانات المميزة',table(['الإعلان','الظهور','تغيير الباقة'],data.ads.filter(a=>a.status==='معتمد').map(a=>[esc(a.title),esc(a.plan),`<select data-featured="${a.id}" aria-label="باقة ${esc(a.title)}">${['Basic','Featured','Premium'].map(p=>`<option ${p===a.plan?'selected':''}>${p}</option>`).join('')}</select>`]))+'<p class="form-note">اختيار الباقة يغير العرض داخل هذه الجلسة فقط، دون رسوم أو نشر خارجي.</p>');
    $('#portalPage').innerHTML=html;
    if(page==='add')bindAdForm();
    if(page==='account')$('#accountForm').addEventListener('submit',event=>{event.preventDefault();notify('تمت معاينة التحديث ضمن جلسة العرض.');});
    if(page==='ads'){$('#adStatusFilter').addEventListener('change',e=>{adFilter=e.target.value;render();});$('#adSearch').addEventListener('change',e=>{adSearch=e.target.value.trim();render();});}
  }
  function bindAdForm(){
    $('#adImages').addEventListener('change',event=>{releaseUploads();const files=[...event.target.files];if(files.length>6||files.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5*1024*1024)){$('#adError').textContent='اختر حتى 6 صور PNG أو JPEG أو WebP، بحجم 5 ميجابايت كحد أقصى للصورة.';event.target.value='';$('#imagePreviews').replaceChildren();return;}$('#adError').textContent='';uploadUrls=files.map(f=>URL.createObjectURL(f));$('#imagePreviews').innerHTML=uploadUrls.map((url,i)=>`<img src="${url}" alt="معاينة الصورة ${i+1}">`).join('');});
    $('#adForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const fields=Object.fromEntries(new FormData(form));const phone=fields.phone.replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[+() -]/g,'');if(!/^\d{8,15}$/.test(phone)||!fields.title.trim()||!fields.district.trim()||!fields.city.trim()||fields.description.trim().length<10){$('#adError').textContent='يرجى إدخال عنوان وموقع ووصف واضح ورقم تواصل من 8 إلى 15 رقمًا.';return;}const ad={...fields,title:fields.title.trim(),price:Number(fields.price),area:Number(fields.area),rooms:Number(fields.rooms),phone,id:Math.max(0,...data.ads.map(a=>a.id))+1,views:0,status:'تحت المراجعة',plan:'Basic',images:[...uploadUrls]};uploadUrls=[];data.ads.push(ad);adFilter='all';adSearch='';nav('ads');dialog('تم إرسال الإعلان للمراجعة','<p>أُضيف الإعلان إلى قائمة المراجعة ضمن جلسة العرض.</p><p class="subtle">لم يُرسل إلى نظام خارجي، ولا يُنشر على الموقع الفعلي.</p><button class="button" data-close-dialog>متابعة</button>');});
  }
  document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;
    if(b.dataset.page){if(b.dataset.page==='logout')logout();else nav(b.dataset.page);}
    else if(b.hasAttribute('data-close-dialog'))$('#portalDialog').close();
    else if(b.dataset.ad){const a=data.ads.find(a=>a.id===Number(b.dataset.ad));dialog(a.title,`${a.images[0]?`<img src="${a.images[0]}" alt="صورة الإعلان">`:''}<p>${esc(a.city)} · ${esc(a.district)}</p><p>${num(a.price)} ريال · ${num(a.area)} م² · ${a.rooms} غرف</p><p>${esc(a.stage)} · ${esc(a.offer)} · ${status(a.status)}</p><p>${esc(a.description)}</p><p class="subtle">${a.status==='معتمد'?'يظهر الإعلان في دليل العرض داخل البوابة. لا نشر خارجي.':'تابع تغير حالة الإعلان من قائمة المراجعة.'}</p>`);}
    else if(b.dataset.upgrade){selectedAd=Number(b.dataset.upgrade);nav('upgrade');}
    else if(b.dataset.plan){const a=data.ads.find(a=>a.id===selectedAd);if(a)a.plan=b.dataset.plan;dialog('اختيار الباقة',`<p>تم اختيار ${esc(b.dataset.plan)} ضمن العرض.</p><p>السعر يحدد لاحقًا. لم تتم عملية دفع أو تفعيل اشتراك.</p><button class="button" data-close-dialog>تم</button>`);}
    else if(b.dataset.approve||b.dataset.reject){const a=data.ads.find(a=>a.id===Number(b.dataset.approve||b.dataset.reject));if(role!=='admin'||a?.status!=='تحت المراجعة')return;a.status=b.dataset.approve?'معتمد':'مرفوض';render();notify(b.dataset.approve?'تم اعتماد الإعلان ضمن جلسة العرض.':'تم رفض الإعلان ضمن جلسة العرض.');}
    else if(b.dataset.leadPage){leadPage+=Number(b.dataset.leadPage);render();}
    else if(b.hasAttribute('data-marketer')){const m=data.marketers[Number(b.dataset.marketer)];m.status=m.status==='نشط'?'معلق':'نشط';render();notify('تم تحديث حالة المسوق في جلسة العرض.');}
    else if(b.dataset.projectDetail){const p=projects.find(p=>p.id===b.dataset.projectDetail);dialog(p.name,unitsTable(units.filter(u=>u.projectId===p.id)));}
  });
  document.addEventListener('change',event=>{const el=event.target;if(el.dataset.leadStatus){data.leads.find(l=>l.id===Number(el.dataset.leadStatus)).status=el.value;notify('تم تحديث حالة العميل ضمن العرض.');}if(el.dataset.featured){data.ads.find(a=>a.id===Number(el.dataset.featured)).plan=el.value;notify('تم تحديث ظهور الإعلان ضمن العرض.');}});
  if(query.get('view')==='admin'){role='admin';page=['analytics','ads','projects','units'].includes(query.get('page'))?query.get('page'):'home';showWorkspace();}
  window.addEventListener('beforeunload',()=>{releaseUploads();data.ads.forEach(a=>a.images.forEach(URL.revokeObjectURL));});
})();
